- name: setup Mysql with medium_db db and remote login
  become: yes
  hosts: all
  tasks:
    - name: Installing Mariadb  and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mariadb-server
       - python3-mysqlclient
      become: yes
    - name: start and enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: creating mariadb user (medium_post)
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: creating medium_db
      mysql_db:
        name: "{{db_name}}"
        state: present
    - name: Enable remote login to mysql
      lineinfile:
         path: /etc/my.cnf.d/mariadb-server.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes
      notify:
         - Restart mariadb
  handlers:
    - name: Restart mariadb
      service:
        name: mariadb
        state: restarted
